import {
  DEFAULT_COORDINATION_POLICY,
  type CoordinationEvent,
  type CoordinationTurn,
  type GetCoordinationRunResponse,
} from "../types.js";
import {
  APPROVING_REVIEW_ARTIFACT,
  CRITIC_AGENT,
  FINALIZER_AGENT,
  PLANNER_AGENT,
  REQUIRED_SECTIONS,
  VALID_FINAL_ARTIFACT,
  VALID_PROPOSAL_ARTIFACT,
} from "./fixtures.js";

const runId = "run-phase3-completed-fixture";
const createdAt = "2026-08-30T03:40:00.000Z";
const completedAt = "2026-08-30T03:41:00.000Z";

const turns: CoordinationTurn[] = [
  {
    id: "turn-proposal",
    runId,
    sequence: 1,
    role: "planner",
    agentId: PLANNER_AGENT.id,
    kind: "initial_proposal",
    status: "committed",
    attemptCount: 1,
    inputArtifactIds: [],
    outputArtifactId: "artifact-proposal",
    lastValidationErrors: [],
    createdAt,
    startedAt: createdAt,
    completedAt,
  },
  {
    id: "turn-review-approve",
    runId,
    sequence: 2,
    role: "critic",
    agentId: CRITIC_AGENT.id,
    kind: "proposal_review",
    status: "committed",
    attemptCount: 1,
    inputArtifactIds: ["artifact-proposal"],
    outputArtifactId: "artifact-review-approve",
    lastValidationErrors: [],
    createdAt,
    startedAt: createdAt,
    completedAt,
  },
  {
    id: "turn-final",
    runId,
    sequence: 3,
    role: "finalizer",
    agentId: FINALIZER_AGENT.id,
    kind: "finalization",
    status: "committed",
    attemptCount: 1,
    inputArtifactIds: ["artifact-proposal", "artifact-review-approve"],
    outputArtifactId: "artifact-final",
    lastValidationErrors: [],
    createdAt,
    startedAt: createdAt,
    completedAt,
  },
];

const eventTypes: CoordinationEvent["type"][] = [
  "run.created",
  "run.started",
  "turn.scheduled",
  "attempt.started",
  "turn.committed",
  "turn.scheduled",
  "attempt.started",
  "turn.committed",
  "review.approved",
  "turn.scheduled",
  "attempt.started",
  "turn.committed",
  "run.completed",
];

/** Redacted, lease-free API fixture retained for Phase 4 UI work. */
export const PHASE3_COMPLETED_RESPONSE: GetCoordinationRunResponse = {
  run: {
    id: runId,
    name: "Completed handoff fixture",
    objective: "Produce a practical launch plan.",
    requiredSections: [...REQUIRED_SECTIONS],
    participants: [
      { role: "planner", agentId: PLANNER_AGENT.id, agentNameSnapshot: "Planner" },
      { role: "critic", agentId: CRITIC_AGENT.id, agentNameSnapshot: "Critic" },
      { role: "finalizer", agentId: FINALIZER_AGENT.id, agentNameSnapshot: "Finaliser" },
    ],
    policy: DEFAULT_COORDINATION_POLICY,
    status: "completed",
    phase: "done",
    revision: 0,
    nextTurnSequence: 4,
    latestProposalArtifactId: "artifact-proposal",
    latestReviewArtifactId: "artifact-review-approve",
    finalArtifactId: "artifact-final",
    version: 8,
    createdAt,
    updatedAt: completedAt,
    startedAt: createdAt,
    completedAt,
  },
  turns,
  attempts: turns.map((turn, index) => ({
    id: `attempt-${index + 1}`,
    runId,
    turnId: turn.id,
    number: 1,
    agentId: turn.agentId,
    status: "succeeded",
    agentRunId: `agent-run-${index + 1}`,
    promptDigest: `sha256:prompt-${index + 1}`,
    outputDigest: `sha256:output-${index + 1}`,
    createdAt,
    finishedAt: completedAt,
  })),
  artifacts: [
    { ...VALID_PROPOSAL_ARTIFACT, runId },
    { ...APPROVING_REVIEW_ARTIFACT, runId },
    { ...VALID_FINAL_ARTIFACT, runId },
  ],
  events: eventTypes.map((type, index) => ({
    id: `event-${index + 1}`,
    runId,
    sequence: index + 1,
    type,
    actor: { type: "system" },
    message: type.replaceAll(".", " "),
    details: {},
    createdAt,
  })),
};
